### ISSUE TITLE
Support GIF originals

### ISSUE THREAD

**Issue by deanmoses** [deanmoses/tacocat-gallery-sam#44]
## Why
 - GIF is still used for animation
 - Existing Zenphoto contains 3 gifs, all of which are animated.  They are:
      - /2018/04-08/ztrain_leaving.gif  
      - /2019/08-06/oracle_park5.gif
      - /2019/06-30/aztec.gif

## Spec
 - **Detail images**
     - Show as an actual GIF in order to see the animation
 - **Thumbnails**
    - Don't care which format but remove animation, I don't want animated thumbnails
 
### Rendering as a GIF on the detail page
Two issues:
  - Resize respects animation
     - I'm not 100% sure that resizing an animated gif would preserve the animation, though Sharp appears to...
     - If it doesn't, I might have to serve the original
     - I would have the image processor stick the original in the derived images bucket at the right versionId, so that it gets permanently cached.
  - Passing through the 'render as GIF' instruction
     - Right now every render of the detail page goes through the derived image generator via a URL like this: https://img.pix.tacocat.com/i/2001/12-31/image.gif?version=vv9VclxCfvYbyVAr_Q2oMiYOblB8dhmf&size=1024
     - Despite the "`.gif`" in the URL, it will always retrieve a JPG; that bit of logic is coded into a Cloudfront Function.  It would need to be updated to pass through GIF as a valid format, but only for detail images (I don't want animated thumbnails).

**Comment by mattiasw** [comment]
Hi! I was adding basic GIF support to ExifReader today and made a search on GitHub to see if someone had mentioned that anywhere. In addition to an old request in a closed ExifReader issue, this one also turned up. Maybe you can handle it just fine with the Sharp library but in case ExifReader can help I just wanted to mention that since version 4.19.0 it now supports getting the width and height of GIF images too.

**Comment by deanmoses** [comment]
Wow, thanks for letting me know, @mattiasw!  I'm going to use this today.
